# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: zarb-cli

before:
  hooks:
    - go mod tidy
    - make bls_prebuilt
builds:
  - id: mac-x64
    main: ./cmd/zarb/
    env:
      - CGO_ENABLED=1
    ldflags:
     - -s -w -X github.com/zarbchain/zarb-go/version.build={{.ShortCommit}} -X github.com/zarbchain/zarb-go/version.semVer={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64

  - id: linux-x64
    main: ./cmd/zarb/
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
    ldflags:
     - -s -w -X github.com/zarbchain/zarb-go/version.build={{.ShortCommit}} -X github.com/zarbchain/zarb-go/version.semVer={{.Version}} -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      
  - id: windows-x64
    main: ./cmd/zarb/
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    ldflags:
     - -s -w -X github.com/zarbchain/zarb-go/version.build={{.ShortCommit}} -X github.com/zarbchain/zarb-go/version.semVer={{.Version}} -extldflags "-static"
    goos:
      - windows
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{.Os}}-zarb"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
