name: releaser


on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build release
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set OS Spesific env
        id: set_os_env
        run: |
          curl -sS https://webinstall.dev/brew | bash
          brew install mingw-w64
          brew install FiloSottile/musl-cross/musl-cross --with-aarch64 --with-arm # --with-mips --with-486

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pwd: ${{ github.workspace }}
