on: [push,pull_request]
name: Unit testing
jobs:
  testingPull:
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        go-version: 1.15.x
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unit tests
      run: make unit_test
  testingPush:
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        go-version: 1.16.x
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unit tests
      run: make unit_test